[package]
name = "rust_vs_python"
version = "0.1.0"
authors = ["Rory Coffey <coffeyrt@gmail.com>"]
edition = "2018"

[lib]
name = "rust_vs_python"
crate-type = ["cdylib"]

[dependencies]
regex = "1"

[dependencies.pyo3]
version = "0.9.1"
features = ["extension-module"]
